### ISSUE TITLE
Support for Todoist Plugin

### ISSUE THREAD

**Issue by shawnduggan** [nikbrunner/obsidian-deep-work-theme#10]
Using the light theme, when in Preview mode, the refresh button on the Todoist plugin is a black block.

<img width="896" alt="Screen Shot 2021-09-13 at 9 49 52 PM" src="https://user-images.githubusercontent.com/3504807/133176046-bcc02a94-b315-42fc-9bf4-0027c0661cc9.png">

Really enjoy this theme - thanks for sharing it!

**Comment by nikbrunner** [comment]
Hi thank you for your Feedback :)
I will look into it!
