### ISSUE TITLE
Something Wrong in Preview mode

### ISSUE THREAD

**Issue by dalparan** [nikbrunner/obsidian-deep-work-theme#11]
Thanks a lot for your works!!, I really enjoy your theme.

But, when I use frontmatter in preview mode, a 'space' is padded left side of first charater of first line.

Thanks again!!

-- Edit Mode
![1](https://user-images.githubusercontent.com/64537398/135943885-f06a8507-a4b9-4023-baf3-de9ae1eacb61.PNG)

-- Preview Mode
![2](https://user-images.githubusercontent.com/64537398/135944391-119eb9f2-a7f8-44a3-8f1d-c7ff9f82ad25.jpg)

**Comment by nikbrunner** [comment]
Alright thank you, I will check it out

**Comment by nikbrunner** [comment]
Fixed with dc3e7cfe5f4eda0a709f58d612d0493ee520abdf
