### ISSUE TITLE
Code block indentation problem

### ISSUE THREAD

**Issue by YangFong** [nikbrunner/obsidian-deep-work-theme#17]
> I don't know English; please excuse typing errors.

I noticed that the first line of the code block would have a little space, just the first line

similar #11 

![image](https://user-images.githubusercontent.com/70502828/144748148-791d33d1-119c-44e0-be5c-3bec3c7a4528.png)

**Comment by nikbrunner** [comment]
I will check that out tonight. Thank you for you report :)

**Comment by nikbrunner** [comment]
Shoud be fixed with dadcd957c2153e3bbfbcf668b98e63d0d98cc699.
You can just update via the MarketPlace
