### ISSUE TITLE
Bullet point lines in edit-mote

### ISSUE THREAD

**Issue by Gnopps** [nikbrunner/obsidian-deep-work-theme#21]
It is great that bullet point lines are now active in preview-mode. Would it be possible to have them showing in edit-mode as well?

![image](https://user-images.githubusercontent.com/16313148/145367824-7398be42-049d-4aa6-91ff-ee8f3594e781.png)

**Comment by nikbrunner** [comment]
Hi Gnopps,
yes definitely. I want to implement them in Legacy Source Editor and Live Preview. This is one of my next steps. :)

**Comment by nikbrunner** [comment]
This is now part of #22

**Comment by nikbrunner** [comment]
I will close this and make it part of #22
