### ISSUE TITLE
Outline list has two line than one line expected

### ISSUE THREAD

**Issue by luzelai** [nikbrunner/obsidian-deep-work-theme#39]
I'm not sure if this is a bug.

I'm pleased to use this great theme. However when I use it with _outliner plugin_. I find that the list backs out and two lines appear instead of just one line as in other themes. If my outline gets complicated, this results in so many lines that it's hard to tell the hierarchy of the outline. You can see it in the following figures.

<img width="747" alt="Deepwork Theme" src="https://user-images.githubusercontent.com/63114964/145688313-8f4507e6-d636-42d1-b708-b055bd7d367d.png">

**deep Work theme behaviour**

<img width="747" alt="Default Theme" src="https://user-images.githubusercontent.com/63114964/145688304-b57b83b7-7899-4332-80f6-3014a8d73a59.png">
**default theme behaviour**

Best Regards

**Comment by nikbrunner** [comment]
This is a clear conflict with the Outliner plugin. I can see if I can solve this conflict on my end, but I can't promise it. I will look into it.
