### ISSUE TITLE
Bug - Back and Forward arrows and Vault title not visible in dark mode

### ISSUE THREAD

**Issue by danieltomasz** [nikbrunner/obsidian-deep-work-theme#5]
Theme use dark colour for those elements, it renders them invisible in the dark theme

![image](https://user-images.githubusercontent.com/7980381/128244483-de148834-2485-4e30-95fd-932ebb777d43.png)
Obsidian v.012.12
OS Linux

**Comment by nikbrunner** [comment]
I will look into it! :)

**Comment by danieltomasz** [comment]
This behaviour appear also on light and dark mode on mac
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/7980381/128351997-cc14f9fb-8820-4978-819c-3af743c6ffa4.png">

(the vault name and back and forward arrows are there, but only slightly visible)

**Comment by danieltomasz** [comment]
I was able to get "forward" and "back" buttons colours back  using this css, the  titlebar text is visible in some vaults, in another  not

```
:root {
  --color-gray-0: #f0f6fc;}
  
.theme-dark {
  --text-titlebar: var(--color-gray-0);
  }
/* 2.1. Title bar */
.titlebar {
 color: var(--text-titlebar);
}

.titlebar-button {
 color: var(--text-titlebar);
}

.titlebar-text {
 color: var(--text-titlebar);
}


.titlebar-inner {
  color: var(--text-titlebar);
}

.titlebar-inner .titlebar-text {
  color: var(--text-titlebar);
}


.titlebar-button {
  opacity: 1;
}

```

**Comment by danieltomasz** [comment]
After few restarts of Obsidian  it seems  to work with repo with emoji too  (maybe it was some cache problem)

**Comment by nikbrunner** [comment]
Thank you very much for your suggested code block, but I want to avoid introducing new variables if not needed. 
I implemented the changes with a [very simple commit](2fe086f3d508c630659bcf92c9e225b8935fdda0) and with existing variables. :)

**Comment by danieltomasz** [comment]
Great! The additional variables I introduced were just simple hack so I knowed which color I am adding; Good that the same effect  was possible to achieve with existing ones!
