### ISSUE TITLE
Checkbox styling in live preview

### ISSUE THREAD

**Issue by Gnopps** [nikbrunner/obsidian-deep-work-theme#55]
When using Reading-view, checkboxes with this style are shown as completed (ticked):

`[-]`

However, when using live-preview they show as empty (not ticked). 

Would it be possible for these checkboxes to show as completed also in live-preview?

**Comment by nikbrunner** [comment]
I will look into it

**Comment by nikbrunner** [comment]
Sorry for getting so late back to you, but I was really swamped with private life and work.. 
Checkboxes which are filled with `-` are now also considered "checked" in Live Preview mode, which is now consistent with the "normal" Preview Mode.

**Comment by Gnopps** [comment]
> 

I absolutely understand and have no expectations :-) Thank you!
