### ISSUE TITLE
Gems of the Year 2021 award

### ISSUE THREAD

**Issue by ericaxu** [nikbrunner/obsidian-deep-work-theme#56]
Hi Nik,

Obsidian dev Silver here. I was not able to find you on our Discord community so I assume you're not there. Could you do me a favor to join and DM Silver for details? Thanks a lot!

If this is too much trouble for you, I can try to email you but it would require some back and forth so would rather do it in a synchronous manner. Thank you!

**Comment by nikbrunner** [comment]
Hi there 👋 
I contacted you on Discord 😊
