### ISSUE TITLE
status bar covers find buttons

### ISSUE THREAD

**Issue by daeh** [nikbrunner/obsidian-deep-work-theme#57]
**Is your feature request related to a problem? Please describe.**
It's hard to use the find buttons because the status bar covers them.

**Describe the solution you'd like**
For the Find dialog to open above the status bar, like it does in the default theme.

**Describe alternatives you've considered**
Status bar could move up when the find dialog opens, rather than the find dialog appearing above, or the status bar could disappear when the find dialog opens.

**Additional context**

Thanks for making this theme, I find it really useful.

In my setup, the path overlay covers the previous/next buttons of the note search. This is related to #53. I wonder if it's possible to have the path overlay move upwards when the search opens, or have it disappear entirely. 

I'm using Obsidian v0.13.19, MacOS 11.6.2.

Thanks!

![CleanShot 2022-01-24 at 14 06 33](https://user-images.githubusercontent.com/12652166/150848793-e93bcc2d-d063-4ad8-beb1-6e8c848dca91.png)

![CleanShot 2022-01-24 at 14 09 57](https://user-images.githubusercontent.com/12652166/150848776-e7385200-4683-4f3f-8e28-47da86653975.png)

**Comment by nikbrunner** [comment]
Hi,
thank you for reporting. :) I reverted the styling of the statusbar to a more simple layout like in the original. The fixed position created to much hassle for what its worth. Lets keep it simple.

**Comment by daeh** [comment]
works great. thanks for the fix!
