### ISSUE TITLE
Pane icons suddenly large

### ISSUE THREAD

**Issue by Gnopps** [nikbrunner/obsidian-deep-work-theme#58]
**Describe the bug**
Pane icons appear large. 

![image](https://user-images.githubusercontent.com/16313148/152746374-fa0803e8-6166-4076-9781-6685631bdf0a.png)

**To Reproduce**
I switched to the default theme and then back again to Deep work. After this the pane icons appear very large and highlighted. 

Sorry can't add much info as I haven't been able to troubleshoot why this happens. Switching to another theme solves the problem but whenever going back to Deep work these big icons appear again.

**Comment by nikbrunner** [comment]
Yeah this is an intentional change. I like the styling now more, but I can try to shrink the overall size a bit

**Comment by Gnopps** [comment]
Thanks for your answer, my mistake then in not noticing this earlier :-) I'll try to find their properties and create a snippet to make them smaller myself then I guess.

**Comment by nikbrunner** [comment]
I will make them a little smaller myself, I think. You can share me your Snippet to consider your preference. :)

**Comment by nikbrunner** [comment]
I shrinked the icons/panes a bit :)
