### ISSUE TITLE
'Link to blocks' do not focus on linked block

### ISSUE THREAD

**Issue by claud3v** [nikbrunner/obsidian-deep-work-theme#59]
👋 Hello

When I click on a 'link to block,' the linked block is not focused on the linked note. The pages open up focused on the top - just like when you click a regular 'Link to Note.'

This behaviour is different than the one from the default theme. 

I have quite a few long notes, and other notes link to various parts of these long notes, so it would be great if the focus were on the linked block when they are open. 

Thank you!

**Comment by claud3v** [comment]
I am closing down this issue, I've tried other themes, and they have the same issue. I guess it's an issue with Obsidian, not the theme.

**Comment by nikbrunner** [comment]
Hi there, 👋 
I know about this issue, but like you said, I can't to anything about that. You can bring it up with the Developers. They are really nice. :)
